version: '3.8'
services:
  db:
    container_name: votsu-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: votsu-db
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  votsu-api:
    stdin_open: true
    build:
      context: .
      dockerfile: 'Dockerfile'
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: votsu-api-v3
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '5000:5000'
volumes:
  pgadmin-data:
