version: '3.8'
services:
  db:
    container_name: votsu-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: votsu-db
    ports:
      - '5432:5432'

  votsu-api:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '5000:5000'
